server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbs:postgresql://localhost:5432/Deneme
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true